time:
	gcc -o timer.o -c timer.c
	gcc -o time.exe timer.o

name:
	gcc -o name.o -c name.c
	gcc -o name.exe name.o

signal:
	gcc -o signal.o -c signal.c
	gcc -o signal.exe signal.o

clean:
	rm *.o
	rm *.exe

